
from data.stock_data_manager import StockDataManager
from correlation_plotter import CorrelationPlotter
import pandas as pd

stock_files = {
    # Previous entries
    "ABB": "StockSenseAI/data/raw/ABB_minute.csv",
    "ADANIENSOL": "StockSenseAI/data/raw/ADANIENSOL_minute.csv",
    "ADANIENT": "StockSenseAI/data/raw/ADANIENT_minute.csv",
    "ADANIGREEN": "StockSenseAI/data/raw/ADANIGREEN_minute.csv",
    "ADANIPORTS": "StockSenseAI/data/raw/ADANIPORTS_minute.csv",
    "ADANIPOWER": "StockSenseAI/data/raw/ADANIPOWER_minute.csv",
    "AMBUJACEM": "StockSenseAI/data/raw/AMBUJACEM_minute.csv",
    "APOLLOHOSP": "StockSenseAI/data/raw/APOLLOHOSP_minute.csv",
    "ASIANPAINT": "StockSenseAI/data/raw/ASIANPAINT_minute.csv",
    "ATGL": "StockSenseAI/data/raw/ATGL_minute.csv",
    "AXISBANK": "StockSenseAI/data/raw/AXISBANK_minute.csv",
    "BAJAJ-AUTO": "StockSenseAI/data/raw/BAJAJ-AUTO_minute.csv",
    "BAJAJFINSV": "StockSenseAI/data/raw/BAJAJFINSV_minute.csv",
    "BAJAJHLDNG": "StockSenseAI/data/raw/BAJAJHLDNG_minute.csv",
    "BAJFINANCE": "StockSenseAI/data/raw/BAJFINANCE_minute.csv",
    "BANKBARODA": "StockSenseAI/data/raw/BANKBARODA_minute.csv",
    "BEL": "StockSenseAI/data/raw/BEL_minute.csv",
    "BHARTIARTL": "StockSenseAI/data/raw/BHARTIARTL_minute.csv",
    "BHEL": "StockSenseAI/data/raw/BHEL_minute.csv",
    "BOSCHLTD": "StockSenseAI/data/raw/BOSCHLTD_minute.csv",
    "BPCL": "StockSenseAI/data/raw/BPCL_minute.csv",
    "BRITANNIA": "StockSenseAI/data/raw/BRITANNIA_minute.csv",
    "CANBK": "StockSenseAI/data/raw/CANBK_minute.csv",
    "CHOLAFIN": "StockSenseAI/data/raw/CHOLAFIN_minute.csv",
    "CIPLA": "StockSenseAI/data/raw/CIPLA_minute.csv",
    "COALINDIA": "StockSenseAI/data/raw/COALINDIA_minute.csv",
    "DABUR": "StockSenseAI/data/raw/DABUR_minute.csv",
    "DIVISLAB": "StockSenseAI/data/raw/DIVISLAB_minute.csv",
    "DLF": "StockSenseAI/data/raw/DLF_minute.csv",
    "DMART": "StockSenseAI/data/raw/DMART_minute.csv",
    "DRREDDY": "StockSenseAI/data/raw/DRREDDY_minute.csv",
    "EICHERMOT": "StockSenseAI/data/raw/EICHERMOT_minute.csv",
    "GAIL": "StockSenseAI/data/raw/GAIL_minute.csv",
    "GODREJCP": "StockSenseAI/data/raw/GODREJCP_minute.csv",
    "GRASIM": "StockSenseAI/data/raw/GRASIM_minute.csv",
    "HAL": "StockSenseAI/data/raw/HAL_minute.csv",
    "HAVELLS": "StockSenseAI/data/raw/HAVELLS_minute.csv",
    "HCLTECH": "StockSenseAI/data/raw/HCLTECH_minute.csv",
    "HDFCBANK": "StockSenseAI/data/raw/HDFCBANK_minute.csv",
    "HDFCLIFE": "StockSenseAI/data/raw/HDFCLIFE_minute.csv",
    "HEROMOTOCO": "StockSenseAI/data/raw/HEROMOTOCO_minute.csv",
    "HINDALCO": "StockSenseAI/data/raw/HINDALCO_minute.csv",
    "HINDUNILVR": "StockSenseAI/data/raw/HINDUNILVR_minute.csv",
    "ICICIBANK": "StockSenseAI/data/raw/ICICIBANK_minute.csv",
    "ICICIGI": "StockSenseAI/data/raw/ICICIGI_minute.csv",
    "ICICIPRULI": "StockSenseAI/data/raw/ICICIPRULI_minute.csv",
    "INDIAVIX": "StockSenseAI/data/raw/INDIA_VIX_minute.csv",
    "INDIGO": "StockSenseAI/data/raw/INDIGO_minute.csv",
    "INDUSINDBK": "StockSenseAI/data/raw/INDUSINDBK_minute.csv",
    "INFY": "StockSenseAI/data/raw/INFY_minute.csv",
    "IOC": "StockSenseAI/data/raw/IOC_minute.csv",
    "IRCTC": "StockSenseAI/data/raw/IRCTC_minute.csv",
    "IRFC": "StockSenseAI/data/raw/IRFC_minute.csv",
    "ITC": "StockSenseAI/data/raw/ITC_minute.csv",
    "JINDALSTEL": "StockSenseAI/data/raw/JINDALSTEL_minute.csv",
    "JIOFIN": "StockSenseAI/data/raw/JIOFIN_minute.csv",
    "JSWENERGY": "StockSenseAI/data/raw/JSWENERGY_minute.csv",
    "JSWSTEEL": "StockSenseAI/data/raw/JSWSTEEL_minute.csv",
    "KOTAKBANK": "StockSenseAI/data/raw/KOTAKBANK_minute.csv",
    "LICI": "StockSenseAI/data/raw/LICI_minute.csv",
    "LODHA": "StockSenseAI/data/raw/LODHA_minute.csv",
    "LT": "StockSenseAI/data/raw/LT_minute.csv",
    "LTIM": "StockSenseAI/data/raw/LTIM_minute.csv",
    "MARUTI": "StockSenseAI/data/raw/MARUTI_minute.csv",
    "MOTHERSON": "StockSenseAI/data/raw/MOTHERSON_minute.csv",
    "NAUKRI": "StockSenseAI/data/raw/NAUKRI_minute.csv",
    "NESTLEIND": "StockSenseAI/data/raw/NESTLEIND_minute.csv",
    "NHPC": "StockSenseAI/data/raw/NHPC_minute.csv",
    "NTPC": "StockSenseAI/data/raw/NTPC_minute.csv",
    "ONGC": "StockSenseAI/data/raw/ONGC_minute.csv",
    "PFC": "StockSenseAI/data/raw/PFC_minute.csv",
    "PIDILITIND": "StockSenseAI/data/raw/PIDILITIND_minute.csv",
    "PNB": "StockSenseAI/data/raw/PNB_minute.csv",
    "POWERGRID": "StockSenseAI/data/raw/POWERGRID_minute.csv",
    "RECLTD": "StockSenseAI/data/raw/RECLTD_minute.csv",
    "RELIANCE": "StockSenseAI/data/raw/RELIANCE_minute.csv",
    "SBILIFE": "StockSenseAI/data/raw/SBILIFE_minute.csv",
    "SBIN": "StockSenseAI/data/raw/SBIN_minute.csv",
    "SHREECEM": "StockSenseAI/data/raw/SHREECEM_minute.csv",
    "SHRIRAMFIN": "StockSenseAI/data/raw/SHRIRAMFIN_minute.csv",
    "SIEMENS": "StockSenseAI/data/raw/SIEMENS_minute.csv",
    "SUNPHARMA": "StockSenseAI/data/raw/SUNPHARMA_minute.csv",
    "TATACONSUM": "StockSenseAI/data/raw/TATACONSUM_minute.csv",
    "TATAMOTORS": "StockSenseAI/data/raw/TATAMOTORS_minute.csv",
    "TATAPOWER": "StockSenseAI/data/raw/TATAPOWER_minute.csv",
    "TCS": "StockSenseAI/data/raw/TCS_minute.csv",
    "TVSMOTOR": "StockSenseAI/data/raw/TVSMOTOR_minute.csv"
}

manager = StockDataManager(stock_files.items())

month = 1
year = 2024

combined = pd.concat([
    manager.get_data_for_month('ABB', month, year)[['return_token']],
    manager.get_data_for_month('ADANIENSOL', month, year)[['return_token']],
    manager.get_data_for_month('ADANIENT', month, year)[['return_token']],
    manager.get_data_for_month('ADANIGREEN', month, year)[['return_token']],
    manager.get_data_for_month('ADANIPORTS', month, year)[['return_token']],
    manager.get_data_for_month('ADANIPOWER', month, year)[['return_token']],
    manager.get_data_for_month('AMBUJACEM', month, year)[['return_token']],
    manager.get_data_for_month('APOLLOHOSP', month, year)[['return_token']],
    manager.get_data_for_month('ASIANPAINT', month, year)[['return_token']],
    manager.get_data_for_month('ATGL', month, year)[['return_token']],
    manager.get_data_for_month('AXISBANK', month, year)[['return_token']],
    manager.get_data_for_month('BAJAJ-AUTO', month, year)[['return_token']],
    manager.get_data_for_month('BAJAJFINSV', month, year)[['return_token']],
    manager.get_data_for_month('BAJAJHLDNG', month, year)[['return_token']],
    manager.get_data_for_month('BAJFINANCE', month, year)[['return_token']],
    manager.get_data_for_month('BANKBARODA', month, year)[['return_token']],
    manager.get_data_for_month('BEL', month, year)[['return_token']],
    manager.get_data_for_month('BHARTIARTL', month, year)[['return_token']],
    manager.get_data_for_month('BHEL', month, year)[['return_token']],
    manager.get_data_for_month('BOSCHLTD', month, year)[['return_token']],
    manager.get_data_for_month('BPCL', month, year)[['return_token']],
    manager.get_data_for_month('BRITANNIA', month, year)[['return_token']],
    manager.get_data_for_month('CANBK', month, year)[['return_token']],
    manager.get_data_for_month('CHOLAFIN', month, year)[['return_token']],
    manager.get_data_for_month('CIPLA', month, year)[['return_token']],
    manager.get_data_for_month('COALINDIA', month, year)[['return_token']],
    manager.get_data_for_month('DABUR', month, year)[['return_token']],
    manager.get_data_for_month('DIVISLAB', month, year)[['return_token']],
    manager.get_data_for_month('DLF', month, year)[['return_token']],
    manager.get_data_for_month('DMART', month, year)[['return_token']],
    manager.get_data_for_month('DRREDDY', month, year)[['return_token']],
    manager.get_data_for_month('EICHERMOT', month, year)[['return_token']],
    manager.get_data_for_month('GAIL', month, year)[['return_token']],
    manager.get_data_for_month('GODREJCP', month, year)[['return_token']],
    manager.get_data_for_month('GRASIM', month, year)[['return_token']],
    manager.get_data_for_month('HAL', month, year)[['return_token']],
    manager.get_data_for_month('HAVELLS', month, year)[['return_token']],
    manager.get_data_for_month('HCLTECH', month, year)[['return_token']],
    manager.get_data_for_month('HDFCBANK', month, year)[['return_token']],
    manager.get_data_for_month('HDFCLIFE', month, year)[['return_token']],
    manager.get_data_for_month('HEROMOTOCO', month, year)[['return_token']],
    manager.get_data_for_month('HINDALCO', month, year)[['return_token']],
    manager.get_data_for_month('HINDUNILVR', month, year)[['return_token']],
    manager.get_data_for_month('ICICIBANK', month, year)[['return_token']],
    manager.get_data_for_month('ICICIGI', month, year)[['return_token']],
    manager.get_data_for_month('ICICIPRULI', month, year)[['return_token']],
    manager.get_data_for_month('INDIAVIX', month, year)[['return_token']],
    manager.get_data_for_month('INDIGO', month, year)[['return_token']],
    manager.get_data_for_month('INDUSINDBK', month, year)[['return_token']],
    manager.get_data_for_month('INFY', month, year)[['return_token']],
    manager.get_data_for_month('IOC', month, year)[['return_token']],
    manager.get_data_for_month('IRCTC', month, year)[['return_token']],
    manager.get_data_for_month('IRFC', month, year)[['return_token']],
    manager.get_data_for_month('ITC', month, year)[['return_token']],
    manager.get_data_for_month('JINDALSTEL', month, year)[['return_token']],
    manager.get_data_for_month('JIOFIN', month, year)[['return_token']],
    manager.get_data_for_month('JSWENERGY', month, year)[['return_token']],
    manager.get_data_for_month('JSWSTEEL', month, year)[['return_token']],
    manager.get_data_for_month('KOTAKBANK', month, year)[['return_token']],
    manager.get_data_for_month('LICI', month, year)[['return_token']],
    manager.get_data_for_month('LODHA', month, year)[['return_token']],
    manager.get_data_for_month('LT', month, year)[['return_token']],
    manager.get_data_for_month('LTIM', month, year)[['return_token']],
    manager.get_data_for_month('MARUTI', month, year)[['return_token']],
    manager.get_data_for_month('MOTHERSON', month, year)[['return_token']],
    manager.get_data_for_month('NAUKRI', month, year)[['return_token']],
    manager.get_data_for_month('NESTLEIND', month, year)[['return_token']],
    manager.get_data_for_month('NHPC', month, year)[['return_token']],
    manager.get_data_for_month('NTPC', month, year)[['return_token']],
    manager.get_data_for_month('ONGC', month, year)[['return_token']],
    manager.get_data_for_month('PFC', month, year)[['return_token']],
    manager.get_data_for_month('PIDILITIND', month, year)[['return_token']],
    manager.get_data_for_month('PNB', month, year)[['return_token']],
    manager.get_data_for_month('POWERGRID', month, year)[['return_token']],
    manager.get_data_for_month('RECLTD', month, year)[['return_token']],
    manager.get_data_for_month('RELIANCE', month, year)[['return_token']],
    manager.get_data_for_month('SBILIFE', month, year)[['return_token']],
    manager.get_data_for_month('SBIN', month, year)[['return_token']],
    manager.get_data_for_month('SHREECEM', month, year)[['return_token']],
    manager.get_data_for_month('SHRIRAMFIN', month, year)[['return_token']],
    manager.get_data_for_month('SIEMENS', month, year)[['return_token']],
    manager.get_data_for_month('SUNPHARMA', month, year)[['return_token']],
    manager.get_data_for_month('TATACONSUM', month, year)[['return_token']],
    manager.get_data_for_month('TATAMOTORS', month, year)[['return_token']],
    manager.get_data_for_month('TATAPOWER', month, year)[['return_token']],
    manager.get_data_for_month('TCS', month, year)[['return_token']],
    manager.get_data_for_month('TVSMOTOR', month, year)[['return_token']]
], axis=1)

plotter = CorrelationPlotter()
plotter.plot(combined)
